name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - run: |
          python -m pip install --upgrade pip
          poetry config virtualenvs.create --unset --local
          poetry install
      - name: Run Ruff
        run: poetry run ruff check --output-format=github .
      - name: Run Ruff format
        run: poetry run ruff format --check .